apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: docker-registry-sops-secret
spec:
    secretTemplates:
        - name: docker-registry-secret
          data:
            .dockerconfigjson: ENC[AES256_GCM,data:sA45Se3fH37rXCiIrleFrWkBKAV6RY+svoGZCHuZXVqdaESKDNqaB7+Yehm51aEFz8YUU+sVx5bKQQn7lYv0qf3Qp8p++u4paifzBmjO2sOcW+afbhYVfYJym/aj7BxjUvcHuylNorSCM7llDSDqT03zEon4Ev6j57MlPKKSAyR1BFiBoqZuA7YbnAI=,iv:cSKfliX0no3WxhLAfZ8pKtKtaLu6uJyMkBfSzg9fziA=,tag:sH6KGc8nG9DSQoAaU4guAw==,type:str]
          type: kubernetes.io/dockerconfigjson
        - name: env-config-secret
          stringData:
            CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:FQBSnt0jgmEwFrEzsWY3MYTX7yrtZDqPpeQAJCNXWDUQZeryRkqs0A==,iv:VsZC9ZjWdRFBdnG1Kt2LV9PLhZrkG8DVrk7OKtiIuwA=,tag:kPy6FLIdmEvloXnHOpK0RA==,type:str]
            CLOUDFLARE_ZONE_ID: ENC[AES256_GCM,data:QUbMrp7UE/xEFRLrOglJk1Q4SyKhgQpj5qcXLuxxCYc=,iv:GwvmikKCigQg/kNNhn8FewKGVimgL/bBTl2l6U33txs=,tag:uuGeBrd2Jp8xYRlE+8jZaQ==,type:str]
            FQDN: ENC[AES256_GCM,data:y4z8ayzXN9ql2BBEDZaxKFddzaQ4,iv:ByYGX9vNh2Il7ZWg31Oq7Yj9wGVlIiVOK1zfJ/iPdnI=,tag:VwsVmq0h72ZQqytxRY4rEw==,type:str]
            DNS_RECORD: ENC[AES256_GCM,data:M1/fx7AsLadT3IXlf3D3ZgkngQtk,iv:xIpWMkcFawzxcPunM89X4zggDZYJzlVYbe5ZV1u6RAU=,tag:LBlrYSSIoL6AGrXDVzs6ew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lc3vm7xf0e563t2rchm6wxa8lp2mrzecg2a0prldzt0z2ga7538qfpkwp6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMUJUNGhlTjhqUExka1Rq
            VWRjQWZOSHh1TnNpamc5R2hxUVE3cjROZURRCmtHZXl2WTl5L0FLTEIrWHlnOWZr
            RHBQV2NCYjFiblFCdnc5dExZZ1BZU1kKLS0tIDlSRTdGWTZsVE9hendLSlUyR2p5
            dWhLL21XZS8zVVcrU1RKTFJENjRMVFkKKgQbubgkY0edfri79LKhjQXrAbbRx6y4
            XhKLQ/iTwzIRQbl2lIRiEQ58SXY4MZO4nNRuoApeVhtm75Ee8tnn7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-18T18:36:13Z"
    mac: ENC[AES256_GCM,data:qoTmNULENSfWLAAyhIEV1u7tMRaSlM0xDuP2UBg6QYAr/pZNsgkzSKP0oA7WRlKICXSHaMaaUT8UA0Mvz8yZC06OZ6nMpY6S6I/fPwLpqsSQvXmFY/NIr0pbeipXwCCWcW3yCUZSQ3w0/HoPHU36lJ7Vh/rgGgbTLHbXma0a4i4=,iv:jpgLjJI2AouBIjab+s1p4ke3zO/c8cyltu1ETFLT8e0=,tag:LAHDqd1MsBKSNzohrzg+hg==,type:str]
    pgp:
        - created_at: "2025-01-18T18:36:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA9GztP6xR+tEAQv/bVxEG7FSGe7rd0bgUb2eyUSbDRFhqGVBZFHFiH0QvDMs
            /NCyUaQbC320QPSLmaApq67NHqSL4L0bAA9MSn9RcYD5hU0VYGQOl/T5GyGkFuE8
            JC4ylDwYpuXpkykD5mhh4OKqQkqfMhMgjwn7Kdujhj4Fx+fO6K5mpkgACNUsRzLN
            zkhAwVH40IUAUj1WZtS/lPwn2fBu9HZXDd2ig7u2O0IH75WVyTBia07yqJQmbMyW
            b5DMLaXjrZHxz0kM2hN8g8BN8XUTx1aIrUTwmVwCOaLaLlOA9AEN97MHEvOR4b4c
            q97aerQspbPGpvfZ5Qsg6b3udtL8EYQ9+Lx4YkFLahjxw2LI+KVmB8iKu6V2Xqef
            /SYtj+IEzJW/LK9ohkPq1tB0gPyxM9W3nM2gJATiO4A+9ljo4JTl8zdZaR7nfMiU
            pPQtLdnpFe+KaWprhYBqtlK6LeuBFb7D6JMx6ync2tJno5W+jEMzKX5PKk217hl6
            64MdsynmdwAXNChg4CVi0l4BQ4KlgV8w/c5hohPaK5vqmYiL021ePGB7AtWW/zMS
            b2/mpkzHfj7Ouxw59siFwxIHZdj/USUDRUGgdnlmRM2zJeYied0v8KvTlbM+IzB8
            7+pP+rJqUAxS0IpmvbcO
            =voCP
            -----END PGP MESSAGE-----
          fp: 4DD454CA8F2056D5F0B7467841E83C8C6C68AC19
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
