apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: docker-registry-sops-secret
spec:
    secretTemplates:
        - name: docker-registry-secret
          data:
            .dockerconfigjson: ENC[AES256_GCM,data:fHBT/j01ibrY628YJbJOyjqZiPa+usEu39euSuR0vPn+H/tL2iBVFaAgZ4kngdGA++qAo/J4ttvz+1fOE5bYTtRRkepsZR3gLVTM/dFocpzhFBoOVdnsvVav88ZgE7zdoYex7mtRt7JIgVBOvbR9pDDLZ0Vzll/yI3EoKhQcx2qtO6SCtaXv4oPOfEo=,iv:6LvHsfE87d6DuhF5r2cdKgwKqQVptNiM8cW0Y1vIJjc=,tag:p+E1WyOJUMKgbmHtEYMoGg==,type:str]
          type: kubernetes.io/dockerconfigjson
        - name: env-config-secret
          stringData:
            CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:5UovMX5ML7c8iFAwde7CmvD7VBWL8zqAv4MXnyiY3s5zHJC08RpaiA==,iv:5+DeiEytWgUhSep9RFp1O5w4R7wCrUmxvTmexGaW6Co=,tag:bhxMorAq0GYdKGiDXNbGOA==,type:str]
            CLOUDFLARE_ZONE_ID: ENC[AES256_GCM,data:MTkhHkiyqoa4jwcWYbrcZA3A60A9LjenM7J0vQvlstE=,iv:f4m1iGbkIVqo9+k47OgdakgS6N2jLFGR7P6T+GSOs00=,tag:KmriHeoiJECC98l26mgEEA==,type:str]
            FQDN: ENC[AES256_GCM,data:Kx6ilmdRh7RCXNZSaUYcl7Vi5hOq,iv:nhomf0OblnRoz/T57cAku/za+ASVFd6iRM4W9+/Rs6M=,tag:BH8E6jeUGI3IUPHgzwQReg==,type:str]
            DNS_RECORD: ENC[AES256_GCM,data:tDYP0CxHXwf5axOui4JHl28w5BhB,iv:OJQfD8IuXwz/zV/gb0J8EsCpqU312j09LM5F3oUMsks=,tag:g9HXwBoTuNLa+RBpdEgF5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cdmjhfczjk8vfe69umnv3vufxhxv3ww3k5405h6f6v9mxhupkepqc03sul
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRXB3UnFmeXBlekd1MURi
            VzFXRnJRRm41ZXl1R3Y1bXNmY20wR2dZRVNjCjBodjA2L3dIdEx1MEI2eFI0NEhQ
            U1JjVTRRZ3RYWXBOcHhQeVl2em5pTFUKLS0tIGdCVnVmV2tpdXI0bldkeDhNOC92
            N010MElWTUwrOG1IS3B6WkhMUTZyQ1kK8Go5P8QuL5IHVTrmFVV73BaNMenmjgNb
            WdwLPVpfTN3A4KIHhlI6UA1D0+m4LNjYY9hz0ghXq+ddqgwMHrs/8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-18T18:05:08Z"
    mac: ENC[AES256_GCM,data:gko4HNg9vRJ8u/75oXuAhM/juimD8J9P5KqF+JmeMjLI7RgvMRRLdczAioAphQu2ABmr6/vVbDWOhdk6UCETA9w+5PexZ8bkI9YtB5CQRdrw/YKVCig4DVOMVD2YzFy6q4gKKf3PuISOYOohQZNwsog0j3awjuOOC58vO9SmnWM=,iv:hA8inO00wCeLXPPfnQrs00LFBKE5wLo9eKLYfIsxXHI=,tag:oEsOlV/cTv2n/awt/tXAYw==,type:str]
    pgp:
        - created_at: "2025-01-18T18:05:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA9GztP6xR+tEAQv/RJ/5aFHmxCk9syzdCeG9uvC413MVRDazLjASuizioQBz
            ITZcp6BMQ5LjPSFKppGS+JfscZl9tuOnPauLo7LWUiU5DHMJ75jgqVwNzfryHWkS
            syy2MaRsOOYGCQ2fY5xuzy2AcTD7y/cYztrM87ISKZqj+9VR/5tfmp2GZwOLoDTI
            IpAUE6NOE+21ifaiemtVqveoGMM5OBPGidP1rBCPqQscNJc3XXuw3FggpxeD7E9R
            zuh41eeZHtQTSxZ8zKhgBtWKXn+l64lxTSygIJG+ZYUv9uJcl/HmpBqo4mp6PPHU
            e91cSAWDSnCjn4W455v8fpSqAm0/50L9uPT9QZZVhJg6rOL38EGlu5imzjHtuWOB
            aoIaT5WqzEbB7hvIwV3VVIDBP6oL1VwUmO9MUEoKb0QFWax8RJxxDR/B+Q6F/1st
            ioB894289GjpKKL/7fGLahP7Gu/76swKDO/Dzf1rnipQVlFFJtJ24z6K4i+QWZTC
            /cRJaj9hYFD1YHRs3ArV0lwBEh/Nc2jnRYhT7SH4lzi42ZDp8hmZ1EmhyopKLg1q
            ucEZcgWzg/4hYfvcJ+qMJabW1Zg9FV0JVvBkUZWn+D9o7WPc8YQjJ1/uYzFkUwHU
            PetoDxMLHVdWi0YBeQ==
            =7MVB
            -----END PGP MESSAGE-----
          fp: 4DD454CA8F2056D5F0B7467841E83C8C6C68AC19
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
