name: Deploy DDNS Anywhere

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: registry.bastian-somon.fr/ddns-anywhere
      HELM_RELEASE: ddns-anywhere
      HELM_NAMESPACE: ddns-anywhere

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build Docker image
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker push $IMAGE_NAME:${{ github.sha }}

      # Deploy to Kubernetes with Helm
      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Deploy using Helm
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "${KUBE_CONFIG_DATA}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig
          helm upgrade --install $HELM_RELEASE ./helm \
            --namespace $HELM_NAMESPACE \
            --set image.tag=${{ github.sha }}
